a=int(input('Enter the value of a:'))
b=int(input('Enter the value of b:'))
print('The value of a+b is ',a+b)
print('The value of a-b is ',a-b)
print('The value of a*b is ',a*b)
print('The value of a/b is ',a/b)
print('The value of a//b is ',a//b)
print('The value of a**b is ',a**b)
print('The value of a%b is ',a%b)
print('The value of a=b is ',a==b)
print('The value of a>b is ',a>b)
print('The value of a<b is ',a<b)
print('The value of a!=b is ',a!=b)
print('The value of a>=b is ',a>=b)
print('The value of a<=b is ',a<=b)
print('The value of a&b is ',a&b)
print('The value of a|b is ',a|b)
print('The value of a is not b is ',a is not b)
print('The value of a is b is ',a is b )